# Generated by Django 2.1.4 on 2019-01-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['name']},
        ),
    ]
